// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	urlMapFieldNames          = builder.RawFieldNames(&UrlMap{})
	urlMapRows                = strings.Join(urlMapFieldNames, ",")
	urlMapRowsExpectAutoSet   = strings.Join(stringx.Remove(urlMapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	urlMapRowsWithPlaceHolder = strings.Join(stringx.Remove(urlMapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUrlMapIdPrefix       = "cache:urlMap:id:"
	cacheUrlMapMd5Prefix      = "cache:urlMap:md5:"
	cacheUrlMapShortUrlPrefix = "cache:urlMap:shortUrl:"
)

type (
	urlMapModel interface {
		Insert(ctx context.Context, data *UrlMap) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UrlMap, error)
		FindOneByMd5(ctx context.Context, md5 string) (*UrlMap, error)
		FindOneByShortUrl(ctx context.Context, shortUrl string) (*UrlMap, error)
		Update(ctx context.Context, data *UrlMap) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUrlMapModel struct {
		sqlc.CachedConn
		table string
	}

	UrlMap struct {
		Id          int64     `db:"id"`
		CreateAt    time.Time `db:"create_at"`
		CreateBy    string    `db:"create_by"`
		IsDeleted   bool      `db:"is_deleted"`
		OriginalUrl string    `db:"original_url"`
		ShortUrl    string    `db:"short_url"`
		Md5         string    `db:"md5"`
	}
)

func newUrlMapModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUrlMapModel {
	return &defaultUrlMapModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`url_map`",
	}
}

func (m *defaultUrlMapModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	urlMapIdKey := fmt.Sprintf("%s%v", cacheUrlMapIdPrefix, id)
	urlMapMd5Key := fmt.Sprintf("%s%v", cacheUrlMapMd5Prefix, data.Md5)
	urlMapShortUrlKey := fmt.Sprintf("%s%v", cacheUrlMapShortUrlPrefix, data.ShortUrl)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, urlMapIdKey, urlMapMd5Key, urlMapShortUrlKey)
	return err
}

func (m *defaultUrlMapModel) FindOne(ctx context.Context, id int64) (*UrlMap, error) {
	urlMapIdKey := fmt.Sprintf("%s%v", cacheUrlMapIdPrefix, id)
	var resp UrlMap
	err := m.QueryRowCtx(ctx, &resp, urlMapIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", urlMapRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUrlMapModel) FindOneByMd5(ctx context.Context, md5 string) (*UrlMap, error) {
	urlMapMd5Key := fmt.Sprintf("%s%v", cacheUrlMapMd5Prefix, md5)
	var resp UrlMap
	err := m.QueryRowIndexCtx(ctx, &resp, urlMapMd5Key, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `md5` = ? limit 1", urlMapRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, md5); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUrlMapModel) FindOneByShortUrl(ctx context.Context, shortUrl string) (*UrlMap, error) {
	urlMapShortUrlKey := fmt.Sprintf("%s%v", cacheUrlMapShortUrlPrefix, shortUrl)
	var resp UrlMap
	err := m.QueryRowIndexCtx(ctx, &resp, urlMapShortUrlKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `short_url` = ? limit 1", urlMapRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, shortUrl); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUrlMapModel) Insert(ctx context.Context, data *UrlMap) (sql.Result, error) {
	urlMapIdKey := fmt.Sprintf("%s%v", cacheUrlMapIdPrefix, data.Id)
	urlMapMd5Key := fmt.Sprintf("%s%v", cacheUrlMapMd5Prefix, data.Md5)
	urlMapShortUrlKey := fmt.Sprintf("%s%v", cacheUrlMapShortUrlPrefix, data.ShortUrl)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, urlMapRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CreateBy, data.IsDeleted, data.OriginalUrl, data.ShortUrl, data.Md5)
	}, urlMapIdKey, urlMapMd5Key, urlMapShortUrlKey)
	return ret, err
}

func (m *defaultUrlMapModel) Update(ctx context.Context, newData *UrlMap) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	urlMapIdKey := fmt.Sprintf("%s%v", cacheUrlMapIdPrefix, data.Id)
	urlMapMd5Key := fmt.Sprintf("%s%v", cacheUrlMapMd5Prefix, data.Md5)
	urlMapShortUrlKey := fmt.Sprintf("%s%v", cacheUrlMapShortUrlPrefix, data.ShortUrl)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, urlMapRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.CreateBy, newData.IsDeleted, newData.OriginalUrl, newData.ShortUrl, newData.Md5, newData.Id)
	}, urlMapIdKey, urlMapMd5Key, urlMapShortUrlKey)
	return err
}

func (m *defaultUrlMapModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUrlMapIdPrefix, primary)
}

func (m *defaultUrlMapModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", urlMapRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUrlMapModel) tableName() string {
	return m.table
}
