CREATE TABLE sequence (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `stub` VARCHAR(4) NOT NULL DEFAULT 'dflt',
    `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `stub` (`stub`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;